Context Provider - balance
UseKeyp/kaching-app pull request #51
Opened 2023-06-26 23:36 UTC by alekseevaiana

closes #49

2023-06-27 19:08 UTC, pi0neerpat requested changes

2023-06-27 19:08 UTC, pi0neerpat commented on context/BalanceContext.tsx
> +      setLoading(false);
All the balances should be returned

```js
const { balances } = useBalance()

console.log(balances) should output all the return objects from the api

2023-06-28 00:26 UTC, alekseevaiana commented
Now balances return an object with all available assets

2023-06-28 18:23 UTC, pi0neerpat requested changes
Looking great! Only thing left is using the context hook for the asset list as well.

2023-06-28 19:49 UTC, alekseevaiana commented
Now we use context provider `const { balances } = useBalance();` in `Balances.tsx` component. Now it fetches when page reloaded and asset changed. It doesn't require refetching when nothing changed. 

https://github.com/UseKeyp/kaching-app/assets/36742189/4f93f7ab-0b97-4f33-b5db-315ac18823a1


https://github.com/UseKeyp/kaching-app/assets/36742189/bd0e54b7-08c0-432f-a355-047bf196f521

2023-06-28 22:24 UTC, pi0neerpat approved these changes
Excellent

2023-06-29 16:24 UTC, merged